### ISSUE TITLE
Couldn't connect to MySQL server when starting docker

### ISSUE THREAD

**Issue by zlylong** [frauhottelmann/daloradius-docker#10]
+ echo #!/bin/bash

+ echo echo "Initialization error" 1>&2

+ DEBIAN_FRONTEND=noninteractive

+ mysqladmin ping -hradius-mysql --silent

+ sleep 20

+ mysqladmin ping -hradius-mysql --silent

+ sleep 20

+ mysqladmin ping -hradius-mysql --silent

+ sleep 20

+ mysqladmin ping -hradius-mysql --silent

+ sleep 20

+ mysqladmin ping -hradius-mysql --silent

+ sleep 20

+ mysqladmin ping -hradius-mysql --silent

+ sleep 20

+ mysqladmin ping -hradius-mysql --silent

**Comment by frauhottelmann** [comment]
I need more information. How are you starting the container?

**Comment by zlylong** [comment]
the docker version is too low 。thinks！
