### ISSUE TITLE
docker run command?

### ISSUE THREAD

**Issue by KamranShahid** [frauhottelmann/daloradius-docker#15]
I am trying following command to run docker image

docker run -it --name daloradius --restart=always -e MYSQL_DATABASE=radius  -e MYSQL_PORT=3306 -e MYSQL_USER=radius  -e MYSQL_PASSWORD=dalodbpass  -e MYSQL_HOST=localhost  -e TZ=Europe/Berlin  frauhottelmann/daloradius-docker

but getting error

Unable to find image 'frauhottelmann/daloradius-docker:latest' locally
docker: Error response from daemon: manifest for frauhottelmann/daloradius-docker:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.

**Comment by KamranShahid** [comment]
when locally copied files and run the docker-compose i was getting same error
then change the tag to 1.2 then things started further

**Comment by frauhottelmann** [comment]
Hey, you have to specify a tag. There is no "latest" tag for my docker images.

**Comment by KamranShahid** [comment]
> Hey, you have to specify a tag. There is no "latest" tag for my docker images.

shouldn't latest tag there? i said i am able to run with 1.2

**Comment by frauhottelmann** [comment]
No, it doesn't have to be. You never know which version of the image your getting or using.
