### ISSUE TITLE
Just little tip for this project

### ISSUE THREAD

**Issue by cuzrawr** [frauhottelmann/daloradius-docker#4]
To access sucessfully runned **frauhottelmann/daloradius-docker**
You need go to:
**http://--address-of-server--/daloradius/login.php**
instead of root path.

_That not obvious apache2 serve not  in /  (root) 
original path in this project is /daloradius_ 

----
also with default username "administrator" and password "radius"

**Comment by frauhottelmann** [comment]
Hi,
yes, I will add this to the readme. Both things are basically inherited from Daloradius.
