### ISSUE TITLE
the userinfo table will be reset

### ISSUE THREAD

**Issue by fflrichard** [frauhottelmann/daloradius-docker#7]
if you start the daloradius and mariadb from docker-compose, and add a user, then stop the dockers, delete the containers, and restart from the docker-compose, and now the userinfo table is empty, but the radcheck table still have the user

**Comment by frauhottelmann** [comment]
Did you delete the mysql/mariadb volume?

**Comment by frauhottelmann** [comment]
The radcheck table is not being deleted during the init of the container, because there that is not present in the SQL file from daloradius. Userinfo is deleted and then seeded again.

**Comment by frauhottelmann** [comment]
Delete
volumes:
      - "./radius-mysql:/var/lib/mysql"
to start completely fresh.
